#!/bin/bash

###
### To disable precommit hook: "git config precommit.disable 1"
###

### Lib

disable=`grep -Pzo '\[precommit\]\s+disable\s+=\s+1' .git/config &> /dev/null || false`
if [ "$disable" ]; then
  exit 0
fi

diff() {
  git diff-index --name-only HEAD
}

grepTypes() {
  res=`diff | grep -Ec "\.($1)$"`
  [[ $res == 0 ]] && return 1 || return 0
}

print() {
  printf "$1" "${@:2}"
}

println() {
  print "$1\n" "${@:2}"
}

msg() {
  print "[precommit] $1: $2" "${@:3}"
}

infom() {
  msg "info" "${@:1}"
}

info() {
  infom "$1\n" "${@:2}"
}

### Main ###

# Lint

if grepTypes "ts|tsx|js|jsx";
then
  infom "Running lint..."

  ./node_modules/.bin/eslint -c ./.eslintrc --quiet `diff | grep -P "\.(ts|tsx|js|jsx)$"` || exit 1

  println "Done."
fi

# Dry compile

if grepTypes "ts|tsx";
then
  infom "Dry compile..."

  ./node_modules/.bin/tsc --noEmit `diff | grep -P "\.(ts|tsx)$"` || exit 1

  println "Done."
fi

# Test

if grepTypes "ts|tsx";
then
  packages=`diff | grep -Eo "packages/\w+" | xargs -I % echo "%/src/.*\\.spec\\.ts" | tr '\n' ' '`

  infom "Testing packages..."

  ./node_modules/.bin/jest -c ./jest.config.js $packages || exit 1

  println "Done."
fi
