#!/usr/bin/env bash

### Header ###

# (i) Hint: use -r option as FIRST ARGUMENT to rebuild cli.

### Lib ###

print() {
  printf "$1" "${@:2}"
}

println() {
  print "$1\n" "${@:2}"
}

msg() {
  print "[cli] $1: $2" "${@:3}"
}

infom() {
  msg "info" "${@:1}"
}

info() {
  infom "$1\n" "${@:2}"
}

function build() {
    infom "Building cli..."
    npx tsc -p ./cli/tsconfig.json
    println "done"
}

### Main ###

args=($@)

if [[ "${args[0]}" == "-r" ]] || [[ ! -d "./cli/dist" ]]; then
  build

  if [[ "${args[0]}" == "-r" ]]; then
    args=(${@:2})
  fi
fi

node ./cli/dist/cli/src/index "${args[@]}"
