name: checks
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - '**.ts'
      - '!**.d.ts'
      - './package.json'

  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.19.0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install root node modules
        run: npm ci

      - name: Install per package node modules
        run: |
          ls packages | while read pkg; do \
            if [[ -f "packages/$pkg/package-lock.json" ]]; then \
              echo "===Pkg: $pkg"; \
              npm ci --prefix packages/$pkg --ignore-scripts; \
            fi \
          done

      - name: Run linter
        run: ./node_modules/.bin/eslint -c ./.eslintrc packages/**/*.ts

      - name: Run tests
        run: |
          LIBJ_SKIP_TEST_LOG=1 ./node_modules/.bin/jest -c ./jest.config.js cli
          LIBJ_SKIP_TEST_LOG=1 ./node_modules/.bin/jest -c ./jest.config.js common
          ls packages | while read pkg; do \
            LIBJ_SKIP_TEST_LOG=1 ./node_modules/.bin/jest -c ./jest.config.js packages/$pkg; \
          done
