name: checks
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'
      - '**.ts'
      - '!**.d.ts'
      - './package.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - '**.ts'
      - '!**.d.ts'
      - './package.json'

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - run: npm ci
      - run: ./node_modules/.bin/eslint -c ./.eslintrc packages/**/*.ts
      - run: LIBJ_SKIP_TEST_LOG=1 ./node_modules/.bin/jest -c ./jest.config.js
