name: checks
on: [push]
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: ./node_modules/.bin/eslint -c ./.eslintrc packages/**/*.ts
