name: checks
on:
  push:
    paths:
      - '**.ts'
      - '!**.d.ts'

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - run: npm ci
      - run: ./node_modules/.bin/eslint -c ./.eslintrc packages/**/*.ts
#      - run: ./node_modules/.bin/jest -c ./jest.config.js
